#pragma once
#include "Token.h"
#include "JsonNode.h"
#include <vector>
#include <stdexcept>

namespace corejson {

class Parser {
public:
    // Takes the tokens generated by the Lexer
    Parser(const std::vector<Token>& tokens);
    
    // Starts the parsing process and returns the Root Node
    JsonNode parse();

private:
    std::vector<Token> m_tokens;
    size_t m_position;

    // Helper functions to navigate tokens
    Token current() const;
    void advance();

    // Functions to build specific JSON structures
    JsonNode parseValue();
    JsonNode parseObject();
    JsonNode parseArray();
};

} // namespace corejson